# Generated by Django 3.1.1 on 2020-09-26 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_auto_20200916_2206'),
        ('additem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.customer')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='additem.item')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.restaurant')),
            ],
        ),
    ]
